export const ADMIN = {
  username: "admin",
  password: "mundial2026"
};

export const SCORING = {
  exactScore: 3,
  outcome: 1,
  perfectGroupOrder: 3,
  groupQualified: 3,
  round16: 7,
  quarterFinal: 10,
  semiFinal: 15,
  finalist: 20,
  champion: 30,
  thirdPlace: 15,
  topScorer: 10,
  goldenBall: 10,
  goldenGlove: 8
};

export const TEAMS = {
  MEX: { name: "Mexico", flag: "🇲🇽" },
  RSA: { name: "Sudafrica", flag: "🇿🇦" },
  KOR: { name: "Corea del Sur", flag: "🇰🇷" },
  CZE: { name: "Republica Checa", flag: "🇨🇿" },
  CAN: { name: "Canada", flag: "🇨🇦" },
  BIH: { name: "Bosnia y Herzegovina", flag: "🇧🇦" },
  QAT: { name: "Qatar", flag: "🇶🇦" },
  SUI: { name: "Suiza", flag: "🇨🇭" },
  BRA: { name: "Brasil", flag: "🇧🇷" },
  MAR: { name: "Marruecos", flag: "🇲🇦" },
  HAI: { name: "Haiti", flag: "🇭🇹" },
  SCO: { name: "Escocia", flag: "SCO" },
  USA: { name: "Estados Unidos", flag: "🇺🇸" },
  PAR: { name: "Paraguay", flag: "🇵🇾" },
  AUS: { name: "Australia", flag: "🇦🇺" },
  TUR: { name: "Turquia", flag: "🇹🇷" },
  GER: { name: "Alemania", flag: "🇩🇪" },
  CUW: { name: "Curazao", flag: "🇨🇼" },
  CIV: { name: "Costa de Marfil", flag: "🇨🇮" },
  ECU: { name: "Ecuador", flag: "🇪🇨" },
  NED: { name: "Holanda", flag: "🇳🇱" },
  JPN: { name: "Japon", flag: "🇯🇵" },
  SWE: { name: "Suecia", flag: "🇸🇪" },
  TUN: { name: "Tunez", flag: "🇹🇳" },
  BEL: { name: "Belgica", flag: "🇧🇪" },
  EGY: { name: "Egipto", flag: "🇪🇬" },
  IRN: { name: "Iran", flag: "🇮🇷" },
  NZL: { name: "Nueva Zelanda", flag: "🇳🇿" },
  ESP: { name: "Espana", flag: "🇪🇸" },
  CPV: { name: "Cabo Verde", flag: "🇨🇻" },
  KSA: { name: "Arabia Saudita", flag: "🇸🇦" },
  URU: { name: "Uruguay", flag: "🇺🇾" },
  FRA: { name: "Francia", flag: "🇫🇷" },
  SEN: { name: "Senegal", flag: "🇸🇳" },
  IRQ: { name: "Irak", flag: "🇮🇶" },
  NOR: { name: "Noruega", flag: "🇳🇴" },
  ARG: { name: "Argentina", flag: "🇦🇷" },
  ALG: { name: "Argelia", flag: "🇩🇿" },
  AUT: { name: "Austria", flag: "🇦🇹" },
  JOR: { name: "Jordania", flag: "🇯🇴" },
  POR: { name: "Portugal", flag: "🇵🇹" },
  COD: { name: "RD Congo", flag: "🇨🇩" },
  UZB: { name: "Uzbekistan", flag: "🇺🇿" },
  COL: { name: "Colombia", flag: "🇨🇴" },
  ENG: { name: "Inglaterra", flag: "🇬🇧" },
  CRO: { name: "Croacia", flag: "🇭🇷" },
  GHA: { name: "Ghana", flag: "🇬🇭" },
  PAN: { name: "Panama", flag: "🇵🇦" }
};

export const GROUPS = {
  A: ["MEX", "RSA", "KOR", "CZE"],
  B: ["CAN", "BIH", "QAT", "SUI"],
  C: ["BRA", "MAR", "HAI", "SCO"],
  D: ["USA", "PAR", "AUS", "TUR"],
  E: ["GER", "CUW", "CIV", "ECU"],
  F: ["NED", "JPN", "SWE", "TUN"],
  G: ["BEL", "EGY", "IRN", "NZL"],
  H: ["ESP", "CPV", "KSA", "URU"],
  I: ["FRA", "SEN", "IRQ", "NOR"],
  J: ["ARG", "ALG", "AUT", "JOR"],
  K: ["POR", "COD", "UZB", "COL"],
  L: ["ENG", "CRO", "GHA", "PAN"]
};

const groupMatchRows = [
  [1, "A", "MEX", "RSA", "11 Jun", "15:00", "Mexico City Stadium"],
  [2, "A", "KOR", "CZE", "11 Jun", "22:00", "Estadio Guadalajara"],
  [3, "B", "CAN", "BIH", "12 Jun", "15:00", "Toronto Stadium"],
  [4, "D", "USA", "PAR", "12 Jun", "21:00", "Los Angeles Stadium"],
  [5, "C", "HAI", "SCO", "13 Jun", "21:00", "Boston Stadium"],
  [6, "D", "AUS", "TUR", "13 Jun", "00:00", "BC Place Vancouver"],
  [7, "C", "BRA", "MAR", "13 Jun", "18:00", "New York New Jersey Stadium"],
  [8, "B", "QAT", "SUI", "14 Jun", "15:00", "San Francisco Bay Area Stadium"],
  [9, "E", "CIV", "ECU", "14 Jun", "19:00", "Toronto Stadium"],
  [10, "E", "GER", "CUW", "14 Jun", "13:00", "Miami Stadium"],
  [11, "F", "NED", "JPN", "14 Jun", "16:00", "Dallas Stadium"],
  [12, "F", "SWE", "TUN", "14 Jun", "22:00", "Houston Stadium"],
  [13, "H", "KSA", "URU", "15 Jun", "18:00", "Kansas City Stadium"],
  [14, "H", "ESP", "CPV", "15 Jun", "12:00", "Philadelphia Stadium"],
  [15, "G", "IRN", "NZL", "15 Jun", "21:00", "Seattle Stadium"],
  [16, "G", "BEL", "EGY", "15 Jun", "15:00", "Los Angeles Stadium"],
  [17, "I", "FRA", "SEN", "16 Jun", "15:00", "Philadelphia Stadium"],
  [18, "I", "IRQ", "NOR", "16 Jun", "18:00", "Boston Stadium"],
  [19, "J", "ARG", "ALG", "16 Jun", "21:00", "Kansas City Stadium"],
  [20, "J", "AUT", "JOR", "17 Jun", "00:00", "Dallas Stadium"],
  [21, "L", "GHA", "PAN", "17 Jun", "19:00", "Miami Stadium"],
  [22, "L", "ENG", "CRO", "17 Jun", "16:00", "Toronto Stadium"],
  [23, "K", "POR", "COD", "17 Jun", "13:00", "Houston Stadium"],
  [24, "K", "UZB", "COL", "17 Jun", "22:00", "New York New Jersey Stadium"],
  [25, "A", "CZE", "RSA", "18 Jun", "12:00", "Atlanta Stadium"],
  [26, "B", "SUI", "BIH", "18 Jun", "15:00", "Los Angeles Stadium"],
  [27, "B", "CAN", "QAT", "18 Jun", "18:00", "BC Place Vancouver"],
  [28, "A", "MEX", "KOR", "18 Jun", "21:00", "Estadio Guadalajara"],
  [29, "C", "BRA", "HAI", "19 Jun", "20:30", "Philadelphia Stadium"],
  [30, "C", "SCO", "MAR", "19 Jun", "18:00", "Kansas City Stadium"],
  [31, "D", "TUR", "PAR", "19 Jun", "23:00", "Seattle Stadium"],
  [32, "D", "USA", "AUS", "19 Jun", "15:00", "Seattle Stadium"],
  [33, "F", "TUN", "JPN", "20 Jun", "16:00", "San Francisco Bay Area Stadium"],
  [34, "E", "GER", "CIV", "20 Jun", "20:00", "Houston Stadium"],
  [35, "F", "NED", "SWE", "20 Jun", "13:00", "Miami Stadium"],
  [36, "E", "ECU", "CUW", "21 Jun", "00:00", "Kansas City Stadium"],
  [37, "H", "URU", "CPV", "21 Jun", "18:00", "Los Angeles Stadium"],
  [38, "H", "ESP", "KSA", "21 Jun", "12:00", "Toronto Stadium"],
  [39, "G", "BEL", "IRN", "21 Jun", "15:00", "New York New Jersey Stadium"],
  [40, "G", "NZL", "EGY", "21 Jun", "21:00", "Dallas Stadium"],
  [41, "I", "NOR", "SEN", "22 Jun", "20:00", "Houston Stadium"],
  [42, "I", "FRA", "IRQ", "22 Jun", "17:00", "Los Angeles Stadium"],
  [43, "J", "ARG", "AUT", "22 Jun", "13:00", "Kansas City Stadium"],
  [44, "J", "JOR", "ALG", "22 Jun", "23:00", "San Francisco Bay Area Stadium"],
  [45, "L", "ENG", "GHA", "23 Jun", "16:00", "New York New Jersey Stadium"],
  [46, "L", "PAN", "CRO", "23 Jun", "19:00", "Toronto Stadium"],
  [47, "K", "POR", "UZB", "23 Jun", "13:00", "Kansas City Stadium"],
  [48, "K", "COL", "COD", "23 Jun", "22:00", "Dallas Stadium"],
  [49, "C", "SCO", "BRA", "24 Jun", "18:00", "Miami Stadium"],
  [50, "C", "MAR", "HAI", "24 Jun", "18:00", "Atlanta Stadium"],
  [51, "B", "SUI", "CAN", "24 Jun", "15:00", "BC Place Vancouver"],
  [52, "B", "BIH", "QAT", "24 Jun", "15:00", "Seattle Stadium"],
  [53, "A", "CZE", "MEX", "24 Jun", "21:00", "Mexico City Stadium"],
  [54, "A", "RSA", "KOR", "24 Jun", "21:00", "Estadio Monterrey"],
  [55, "E", "CUW", "CIV", "25 Jun", "16:00", "Dallas Stadium"],
  [56, "E", "ECU", "GER", "25 Jun", "16:00", "New York New Jersey Stadium"],
  [57, "F", "JPN", "SWE", "25 Jun", "19:00", "Boston Stadium"],
  [58, "F", "TUN", "NED", "25 Jun", "19:00", "San Francisco Bay Area Stadium"],
  [59, "D", "TUR", "USA", "25 Jun", "22:00", "Los Angeles Stadium"],
  [60, "D", "PAR", "AUS", "25 Jun", "22:00", "BC Place Vancouver"],
  [61, "I", "NOR", "FRA", "26 Jun", "15:00", "Boston Stadium"],
  [62, "I", "SEN", "IRQ", "26 Jun", "15:00", "Toronto Stadium"],
  [63, "G", "EGY", "IRN", "26 Jun", "23:00", "Seattle Stadium"],
  [64, "G", "NZL", "BEL", "26 Jun", "23:00", "Los Angeles Stadium"],
  [65, "H", "CPV", "KSA", "26 Jun", "20:00", "Houston Stadium"],
  [66, "H", "URU", "ESP", "26 Jun", "20:00", "Atlanta Stadium"],
  [67, "L", "PAN", "ENG", "27 Jun", "17:00", "Miami Stadium"],
  [68, "L", "CRO", "GHA", "27 Jun", "17:00", "Philadelphia Stadium"],
  [69, "J", "ALG", "AUT", "27 Jun", "22:00", "Dallas Stadium"],
  [70, "J", "JOR", "ARG", "27 Jun", "22:00", "New York New Jersey Stadium"],
  [71, "K", "COL", "POR", "27 Jun", "19:30", "Miami Stadium"],
  [72, "K", "COD", "UZB", "27 Jun", "19:30", "Philadelphia Stadium"]
];

export const MATCHES = groupMatchRows.map(([id, group, home, away, date, time, venue]) => ({
  id,
  stage: "groups",
  label: `Grupo ${group}`,
  group,
  home,
  away,
  date: `${date} 2026`,
  time,
  venue
}));

export const KNOCKOUT = [
  { id: 73, stage: "r32", label: "Dieciseisavos", homeSlot: "2A", awaySlot: "2B", date: "28 Jun 2026", time: "15:00", venue: "Los Angeles Stadium" },
  { id: 74, stage: "r32", label: "Dieciseisavos", homeSlot: "1E", awaySlot: "3ABCDF", date: "29 Jun 2026", time: "16:30", venue: "Boston Stadium" },
  { id: 75, stage: "r32", label: "Dieciseisavos", homeSlot: "1F", awaySlot: "2C", date: "29 Jun 2026", time: "21:00", venue: "Estadio Monterrey" },
  { id: 76, stage: "r32", label: "Dieciseisavos", homeSlot: "1C", awaySlot: "2F", date: "29 Jun 2026", time: "13:00", venue: "Houston Stadium" },
  { id: 77, stage: "r32", label: "Dieciseisavos", homeSlot: "1I", awaySlot: "3CDFGH", date: "30 Jun 2026", time: "17:00", venue: "New York New Jersey Stadium" },
  { id: 78, stage: "r32", label: "Dieciseisavos", homeSlot: "2E", awaySlot: "2I", date: "30 Jun 2026", time: "13:00", venue: "Dallas Stadium" },
  { id: 79, stage: "r32", label: "Dieciseisavos", homeSlot: "1A", awaySlot: "3CEFHI", date: "30 Jun 2026", time: "21:00", venue: "Mexico City Stadium" },
  { id: 80, stage: "r32", label: "Dieciseisavos", homeSlot: "1L", awaySlot: "3EHIJK", date: "1 Jul 2026", time: "12:00", venue: "Atlanta Stadium" },
  { id: 81, stage: "r32", label: "Dieciseisavos", homeSlot: "1D", awaySlot: "3BEFIJ", date: "1 Jul 2026", time: "20:00", venue: "San Francisco Bay Area Stadium" },
  { id: 82, stage: "r32", label: "Dieciseisavos", homeSlot: "1G", awaySlot: "3AEHIJ", date: "1 Jul 2026", time: "16:00", venue: "Seattle Stadium" },
  { id: 83, stage: "r32", label: "Dieciseisavos", homeSlot: "2K", awaySlot: "2L", date: "2 Jul 2026", time: "19:00", venue: "Toronto Stadium" },
  { id: 84, stage: "r32", label: "Dieciseisavos", homeSlot: "1H", awaySlot: "2J", date: "2 Jul 2026", time: "15:00", venue: "Los Angeles Stadium" },
  { id: 85, stage: "r32", label: "Dieciseisavos", homeSlot: "1B", awaySlot: "3EFGIJ", date: "2 Jul 2026", time: "23:00", venue: "BC Place Vancouver" },
  { id: 86, stage: "r32", label: "Dieciseisavos", homeSlot: "1J", awaySlot: "2H", date: "3 Jul 2026", time: "18:00", venue: "Miami Stadium" },
  { id: 87, stage: "r32", label: "Dieciseisavos", homeSlot: "1K", awaySlot: "3DEIJL", date: "3 Jul 2026", time: "21:30", venue: "Kansas City Stadium" },
  { id: 88, stage: "r32", label: "Dieciseisavos", homeSlot: "2D", awaySlot: "2G", date: "3 Jul 2026", time: "14:00", venue: "Dallas Stadium" },
  { id: 89, stage: "r16", label: "Octavos", homeSlot: "W74", awaySlot: "W77", date: "4 Jul 2026", time: "17:00", venue: "Philadelphia Stadium" },
  { id: 90, stage: "r16", label: "Octavos", homeSlot: "W73", awaySlot: "W75", date: "4 Jul 2026", time: "13:00", venue: "Houston Stadium" },
  { id: 91, stage: "r16", label: "Octavos", homeSlot: "W76", awaySlot: "W78", date: "5 Jul 2026", time: "16:00", venue: "New York New Jersey Stadium" },
  { id: 92, stage: "r16", label: "Octavos", homeSlot: "W79", awaySlot: "W80", date: "5 Jul 2026", time: "20:00", venue: "Mexico City Stadium" },
  { id: 93, stage: "r16", label: "Octavos", homeSlot: "W83", awaySlot: "W84", date: "6 Jul 2026", time: "15:00", venue: "Dallas Stadium" },
  { id: 94, stage: "r16", label: "Octavos", homeSlot: "W81", awaySlot: "W82", date: "6 Jul 2026", time: "20:00", venue: "Seattle Stadium" },
  { id: 95, stage: "r16", label: "Octavos", homeSlot: "W86", awaySlot: "W88", date: "7 Jul 2026", time: "12:00", venue: "Atlanta Stadium" },
  { id: 96, stage: "r16", label: "Octavos", homeSlot: "W85", awaySlot: "W87", date: "7 Jul 2026", time: "16:00", venue: "BC Place Vancouver" },
  { id: 97, stage: "qf", label: "Cuartos", homeSlot: "W89", awaySlot: "W90", date: "9 Jul 2026", time: "16:00", venue: "Boston Stadium" },
  { id: 98, stage: "qf", label: "Cuartos", homeSlot: "W93", awaySlot: "W94", date: "10 Jul 2026", time: "15:00", venue: "Los Angeles Stadium" },
  { id: 99, stage: "qf", label: "Cuartos", homeSlot: "W91", awaySlot: "W92", date: "11 Jul 2026", time: "17:00", venue: "Miami Stadium" },
  { id: 100, stage: "qf", label: "Cuartos", homeSlot: "W95", awaySlot: "W96", date: "11 Jul 2026", time: "21:00", venue: "Kansas City Stadium" },
  { id: 101, stage: "sf", label: "Semifinal", homeSlot: "W97", awaySlot: "W98", date: "14 Jul 2026", time: "15:00", venue: "Dallas Stadium" },
  { id: 102, stage: "sf", label: "Semifinal", homeSlot: "W99", awaySlot: "W100", date: "15 Jul 2026", time: "15:00", venue: "Atlanta Stadium" },
  { id: 103, stage: "third", label: "Tercer puesto", homeSlot: "L101", awaySlot: "L102", date: "18 Jul 2026", time: "17:00", venue: "Miami Stadium" },
  { id: 104, stage: "final", label: "Final", homeSlot: "W101", awaySlot: "W102", date: "19 Jul 2026", time: "15:00", venue: "New York New Jersey Stadium" }
];
